name: Playwright Tests

on:
  workflow_run:
    workflows: [Unit Tests]
    types: [completed]
    branches: [main, develop]

jobs:
  test:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
      NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
      NEXT_PUBLIC_CONVEX_URL: ${{ secrets.NEXT_PUBLIC_CONVEX_URL }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Restore bun cache
        uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Install dependencies
        run: bun install

      - name: Install Playwright Browsers
        run: bunx playwright install --with-deps

      - name: Run Playwright tests
        run: bun run test:e2e

      - name: Upload blob report to GitHub Actions Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: blob-report
          path: blob-report
          retention-days: 1

      - name: Notify Vercel
        uses: vercel/repository-dispatch/actions/status@v1
        if: success()
        with:
          name: Vercel - yellow-web: playwright tests

      - name: Notify Vercel
        uses: vercel/repository-dispatch/actions/status@v1
        if: success()
        with:
          name: Vercel - yellow-landing-page: playwright tests
